title: Mentored Sprints
baseurl: /
permalink: "/:title/"
collections:
  posts:
    permalink: "/posts/:title/"
palette: blue
header:
  title: Mentored sprints
  logo_img: images/logo/logo-alt.png
  has_nav: true
  nav_links:
    - label: Home
      url: /
    - label: Events
      url: /events
    - label: Organisers
      url: /getstarted
    - label: Community Handbook
      url: /handbook/
footer:
  logo_img: images/logo/logo-alt.svg
  # tagline:
  has_nav: true
  nav_title: Mentored Sprints
  nav_links:
    - label: About Us
      url: /about
    # - label: Blog
    #   url: /blog
    - label: Organise a Sprint
      url: /getstarted
    - label: Contact
      url: /contact
    - label: Brand
      url: /brand
  has_social: true
  social_title: Community
  social_links:
    - label: Twitter
      url: "https://twitter.com/MentoredSprints"
      new_window: true
    # - label: Discord
    #   url: "https://www.instagram.com/"
    #   new_window: true
    - label: GitHub
      url: "https://github.com/pycon-mentored-sprints"
      new_window: true
  has_subscribe: false
  subscribe_title: Newsletter
  subscribe_content: Stay up to date with upcoming sprints and developments. Join our mailing list here!
  content: "&copy; Mentored Sprints 2018-2020 | "
  links:
    - label: GitHub source
      url: "https://github.com/pycon-mentored-sprints/mentored-sprints.dev"
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
include:
  - _redirects
