title: Mentored Sprints
baseurl: /
permalink: "/:title/"
collections:
  posts:
    permalink: "/posts/:title/"
palette: blue
header:
  title: Mentored sprints
  logo_img: images/logo/logo_alt.svg
  has_nav: true
  nav_links:
    - label: Home
      url: /
    - label: Events
      url: /events
    - label: Pricing
      url: /pricing
    - label: Style Guide
      url: /style-guide
    - label: Sign Up
      url: /signup
      primary: true
footer:
  logo_img: images/logo/logo_alt.svg
  # tagline:
  has_nav: true
  nav_title: Mentored Sprints
  nav_links:
    - label: About Us
      url: /about
    - label: Blog
      url: /blog
    - label: Sign Up
      url: signup
    - label: Contact
      url: /contact
  has_social: true
  social_title: Community
  social_links:
    - label: Twitter
      url: "https://twitter.com/MentoredSprints"
      new_window: true
    - label: Discord
      url: "https://www.instagram.com/"
      new_window: true
    # - label: LinkedIn
    #   url: 'https://www.linkedin.com/'
    #   new_window: true
  has_subscribe: true
  subscribe_title: Subscribe
  subscribe_content: Stay up to date with upcoming sprints and developments. Join our mailing list here!
  content: "&copy; Mentored Sprints 2018-2020"
  links:
    - label: Mentored Sprints
      url: "https://www.mentoredsprints.dev"
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
