[build]
    publish = "_site"
    command = "jekyll build"

[[redirects]]
    from = "https://mentored-sprints.dev/handbook"
    to = "https://mentored-sprints.netlify.app"
    status = 301
    force = true