name: Check site

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - feature/*

jobs:
  diff-site:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        name: Checkout repo
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: actions/setup-node@v1
        name: Setup node
        with:
          node-version: "12"
      - run: npm install pa11y-ci
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
        name: setup Ruby
      - run: |
          gem install bundler jekyll
          bundle install
          bundle exec jekyll build
          bundle exec jekyll serve 
          npm run test-pa11y
          pkill -f jekyll
